/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/displays/Floorstand 3S.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Floorstand 3S.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.002, 1.05, -0.121]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes['header-fluting'].geometry} material={materials.fluting} />
        <mesh geometry={nodes['header-header'].geometry} material={materials.header} />
        <mesh geometry={nodes['header-inside'].geometry} material={materials.inside} />
      </group>
      <group position={[0, 0.824, 0.03]}>
        <mesh geometry={nodes['shelf_1-fluting'].geometry} material={materials.fluting} />
        <mesh geometry={nodes['shelf_1-inside'].geometry} material={materials.inside} />
        <mesh geometry={nodes['shelf_1-shelf1'].geometry} material={materials.shelf1} />
        <mesh geometry={nodes.shelf_1_dropzone.geometry} material={materials.shelf3} position={[0, 0.015, -0.002]} />
      </group>
      <group position={[0, 0.469, 0.03]}>
        <mesh geometry={nodes['shelf_2-fluting'].geometry} material={materials.fluting} />
        <mesh geometry={nodes['shelf_2-inside'].geometry} material={materials.inside} />
        <mesh geometry={nodes['shelf_2-shelf2'].geometry} material={materials.shelf2} />
        <mesh geometry={nodes.shelf_2_dropzone.geometry} material={materials['Wireframe.001']} position={[0, 0.016, -0.002]} />
      </group>
      <group position={[-0.039, 0.092, 0.038]}>
        <mesh geometry={nodes['shelf_3-fluting'].geometry} material={materials.fluting} />
        <mesh geometry={nodes['shelf_3-inside'].geometry} material={materials.inside} />
        <mesh geometry={nodes['shelf_3-shelf3'].geometry} material={materials.shelf3} />
        <mesh geometry={nodes.shelf_3_dropzone.geometry} material={nodes.shelf_3_dropzone.material} position={[0.039, 0.038, -0.01]} />
      </group>
      <mesh geometry={nodes['Floorstand_3S-floorstand'].geometry} material={materials.floorstand} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes['Floorstand_3S-fluting'].geometry} material={materials.fluting} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes['Floorstand_3S-inside'].geometry} material={materials.inside} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Floorstand 3S.glb')
